name: tekartik_rpc_repo_support
description: Web socket support project
version: 0.0.1
publish_to: none
# homepage: https://www.example.com
#

environment:
  sdk: ^3.5.0

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  dev_build:
  test: '>=1.6.0'
  process_run:
  path:
  lints: '>=2.0.0'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
