name: tekartik_rpc
description: Abstract Remote Procedure Call.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  path: ">=1.9.0"
  json_rpc_2:
  meta: ">=1.15.0"
  cv: ">=1.1.0+4"
  tekartik_web_socket_io:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket_io
    version: '>=0.2.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  tekartik_web_socket:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket

dev_dependencies:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
  test: ">=1.24.0"
  lints: ">=5.0.0"
resolution: workspace
