name: tekartik_rpc
description: Abstract Remote Procedure Call.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.7.0
  json_rpc_2:
  meta:
  cv:
  tekartik_web_socket_io:
    git:
      url: https://github.com/tekartik/web_socket.dart
      ref: dart3a
      path: web_socket_io
    version: '>=0.2.0'

dev_dependencies:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'
  test:
